import { SaleItem } from './sale-item.model';
import { SaleDocumentStatus, SaleDocumentType } from './sale-document.model';
import { SalePaymentMethod } from './sale-payment-method.model';
import { SaleVoidCashEffect } from './sale-void-cash-effect.model';

export interface Sale {
  id: number;
  businessDate: string | null;
  timeZoneIdSnapshot: string | null;
  createdAt: string;
  status: string;
  paymentMethod: SalePaymentMethod;
  cashSessionId: number | null;
  documentType: SaleDocumentType;
  documentStatus: SaleDocumentStatus;
  number: string | null;
  establishmentCodeSnapshot: string | null;
  emissionPointCodeSnapshot: string | null;
  sequential: number | null;
  documentIssuedAt: string | null;
  accessKey: string | null;
  authorizationNumber: string | null;
  authorizedAt: string | null;
  sriEnvironment: number | null;
  sriEmissionType: number | null;
  sriNumericCode: string | null;
  sriXmlGeneratedAt: string | null;
  hasSriXmlDraft: boolean;
  sriSignedAt: string | null;
  hasSriSignedXml: boolean;
  sriSignatureHash: string | null;
  sriSigningCertificateThumbprint: string | null;
  sriSigningCertificateSubject: string | null;
  sriSigningCertificateSerialNumber: string | null;
  sriSubmittedAt: string | null;
  sriReceptionStatus: string | null;
  sriAuthorizationStatus: string | null;
  sriLastSubmissionError: string | null;
  sriLastCheckedAt: string | null;
  customerName: string | null;
  customerIdentification: string | null;
  customerEmail: string | null;
  buyerNameSnapshot: string | null;
  buyerIdentificationTypeSnapshot: string | null;
  buyerIdentificationSnapshot: string | null;
  buyerAddressSnapshot: string | null;
  buyerEmailSnapshot: string | null;
  notes: string | null;
  grossSubtotal: number;
  discountAmount: number;
  subtotal: number;
  taxAmount: number;
  vat15Subtotal: number;
  vat5Subtotal: number;
  vat0Subtotal: number;
  vatExemptSubtotal: number;
  vatNotSubjectSubtotal: number;
  total: number;
  createdBy: string | null;
  isVoided: boolean;
  voidedAt: string | null;
  voidedByUserId: number | null;
  voidedByUsername: string | null;
  voidReason: string | null;
  voidBusinessDate: string | null;
  voidTimeZoneIdSnapshot: string | null;
  voidCashEffect: SaleVoidCashEffect | null;
  voidCashSessionId: number | null;
  voidCashMovementId: number | null;
  items: SaleItem[];
}
