import { SaleItem } from './sale-item.model';
import { SaleDocumentStatus, SaleDocumentType } from './sale-document.model';

export interface Sale {
  id: number;
  businessDate: string | null;
  timeZoneIdSnapshot: string | null;
  createdAt: string;
  status: string;
  documentType: SaleDocumentType;
  documentStatus: SaleDocumentStatus;
  number: string | null;
  establishmentCodeSnapshot: string | null;
  emissionPointCodeSnapshot: string | null;
  sequential: number | null;
  documentIssuedAt: string | null;
  accessKey: string | null;
  authorizationNumber: string | null;
  authorizedAt: string | null;
  sriEnvironment: number | null;
  sriEmissionType: number | null;
  sriNumericCode: string | null;
  sriXmlGeneratedAt: string | null;
  hasSriXmlDraft: boolean;
  sriSignedAt: string | null;
  hasSriSignedXml: boolean;
  sriSignatureHash: string | null;
  sriSigningCertificateThumbprint: string | null;
  sriSigningCertificateSubject: string | null;
  sriSigningCertificateSerialNumber: string | null;
  sriSubmittedAt: string | null;
  sriReceptionStatus: string | null;
  sriAuthorizationStatus: string | null;
  sriLastSubmissionError: string | null;
  sriLastCheckedAt: string | null;
  customerName: string | null;
  customerEmail: string | null;
  notes: string | null;
  grossSubtotal: number;
  discountAmount: number;
  subtotal: number;
  taxAmount: number;
  vat15Subtotal: number;
  vat5Subtotal: number;
  vat0Subtotal: number;
  vatExemptSubtotal: number;
  vatNotSubjectSubtotal: number;
  total: number;
  createdBy: string | null;
  isVoided: boolean;
  items: SaleItem[];
}
