export const PERMISSIONS = {
  catalogCategoriesRead: 'CATALOG_CATEGORIES_READ',
  catalogCategoriesWrite: 'CATALOG_CATEGORIES_WRITE',
  catalogProductsRead: 'CATALOG_PRODUCTS_READ',
  catalogProductsWrite: 'CATALOG_PRODUCTS_WRITE',
  operationalStructureRead: 'OP_STRUCTURE_READ',
  operationalStructureWrite: 'OP_STRUCTURE_WRITE',
  adminUsersRead: 'ADMIN_USERS_READ',
  adminUsersWrite: 'ADMIN_USERS_WRITE',
  adminRolesRead: 'ADMIN_ROLES_READ',
  adminRolesWrite: 'ADMIN_ROLES_WRITE',
  posSalesCreate: 'POS_SALES_CREATE',
  posSalesVoid: 'POS_SALES_VOID',
  reportsSalesRead: 'REPORTS_SALES_READ',
  sriDocumentsSign: 'SRI_DOCUMENTS_SIGN',
  sriDocumentsSubmit: 'SRI_DOCUMENTS_SUBMIT',
  fiscalSettingsRead: 'FISCAL_SETTINGS_READ',
  fiscalSettingsWrite: 'FISCAL_SETTINGS_WRITE',
  inventoryRead: 'INVENTORY_READ',
  inventoryWrite: 'INVENTORY_WRITE',
} as const;
